name: Pylint

on: [push]

jobs:
  Run-on-Ubuntu:
    name: "Run on Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt install ffmpeg
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: 'Test run of video downloader'
      run: |
        python ytdl.py 'https://www.youtube.com/watch?v=0EqSXDwTq6U&pp=ygUVY2hhcmxpZSBiaXQgbXkgZmluZ2Vy'
    - name: 'Test run of playlist downloader'
      run: |
        python pldl.py 'https://www.youtube.com/playlist?list=PLHy7G7ndrUmpWqBkNKjJRT5urGiPW63Iq'

  Run-on-Windows:
    name: "Run on Windows"
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: 'Test run of video downloader'
      run: |
        python ytdl.py 'https://www.youtube.com/watch?v=0EqSXDwTq6U&pp=ygUVY2hhcmxpZSBiaXQgbXkgZmluZ2Vy'
    - name: 'Test run of playlist downloader'
      run: |
        python pldl.py 'https://www.youtube.com/playlist?list=PLHy7G7ndrUmpWqBkNKjJRT5urGiPW63Iq'

